### ISSUE TITLE
Feature Request: Filter by Family

### ISSUE THREAD

**Issue by dig412** [oavdeev/instaguide.io#1]
Thanks for making instaguide - it's the best instance price guide by far!

I'd really like to be able to filter which instance families are shown in the table - I often want to compare m5/c5/t3 instances for example, and don't want to see the GPU instances.

I had a go at implementing this but got stuck on the interface - I couldn't find a good multi-select library component that worked with Inferno.

**Comment by oavdeev** [comment]
Hey Doug, that was on my list for a while as well! I happened to have some time today, so I've just added basic filtering support, check it out.

I didn't go for a full blown multi-select control, they have so many families I felt it may be a bit cumbersome to choose ones you want from a long list. Instead, you can click on the filter icon next to instance type column header, and just type in a list of search filters. For example, "m5 c5 t3" will work for your example.

**Comment by dig412** [comment]
Thanks Oleg, that works really well!

**Comment by dig412** [comment]
Just dropping in to say how useful this feature is - especially with all the `a` `d` `n` `dn` families that have been added recently.

Thanks very much for this, and for instaguide in general.
